-- Source: Customer On-Time Shipment Analysis Report
SELECT
  "V_RELEASES_COMB"."ITEMNO",
  "V_RELEASES_COMB"."REV",
  "V_RELEASES_COMB"."DESCRIP",
  "V_RELEASES_COMB"."ORDERNO",
  "V_RELEASES_COMB"."PONO",
  "V_RELEASES_COMB"."RELEASE_QUAN",
  "V_RELEASES_COMB"."REQUEST_DATE",
  "V_RELEASES_COMB"."PROMISE_DATE",
  "V_RELEASES_COMB"."SHIP_DATE",
  "V_RELEASES_COMB"."CUSTNO",
  "V_RELEASES_COMB"."COMPANY",
  "V_RELEASES_COMB"."DAYS_DIFF",
  "V_RELEASES_COMB"."CUMM_SHIPPED",
  "V_RELEASES_COMB"."EPLANT_ID",
  "EPLANT"."COMPANY",
  "V_RELEASES_COMB"."ACTUAL_SHIPDATE"
FROM
  "IQMS"."V_RELEASES_COMB" "V_RELEASES_COMB"
  LEFT OUTER JOIN "IQMS"."EPLANT" "EPLANT"
    ON "V_RELEASES_COMB"."EPLANT_ID" = "EPLANT"."ID"
WHERE
  "V_RELEASES_COMB"."CUMM_SHIPPED" > 0
ORDER BY
  "V_RELEASES_COMB"."CUSTNO";
