-- Source: Crystal Report "Open Order Backlog with Pricing"
SELECT
  "V_ORD_DTL_AVALIABILITY"."SHIP_QUAN",
  "V_ORD_DTL_AVALIABILITY"."DESCRIPTION",
  "V_ORD_DTL_AVALIABILITY"."ITEMNO",
  "ORDERS"."PONO",
  "V_ORD_DTL_AVALIABILITY"."UNIT_PRICE",
  "ORDERS"."CURRENCY_ID",
  "CURRENCY"."DESCRIP",
  "CURRENCY"."SPOT_RATE",
  "V_ORD_DTL_AVALIABILITY"."ORDERNO",
  "V_ORD_DTL_AVALIABILITY"."PROMISE_DATE",
  "RELEASES"."FORECAST",
  "V_ORD_DTL_AVALIABILITY"."EPLANT_ID",
  "EPLANT"."COMPANY",
  "ORD_DETAIL"."MISC_ITEMNO",
  "V_ORD_DTL_AVALIABILITY"."ARINVT_ID",
  "ORD_DETAIL"."MISC_ITEM",
  "CURRENCY"."ID",
  "V_ORD_DTL_AVALIABILITY"."COMPANY",
  "V_ORD_DTL_AVALIABILITY"."MUST_SHIP_DATE",
  "RELEASES"."DATE_TYPE",
  "V_ORD_DTL_AVALIABILITY"."REQUEST_DATE",
  "ORD_DETAIL"."ONHOLD"
FROM (((((
  "IQMS"."V_ORD_DTL_AVALIABILITY" "V_ORD_DTL_AVALIABILITY"
  LEFT OUTER JOIN "IQMS"."ORDERS" "ORDERS"
    ON "V_ORD_DTL_AVALIABILITY"."ORDERS_ID" = "ORDERS"."ID"
) LEFT OUTER JOIN "IQMS"."RELEASES" "RELEASES"
  ON "V_ORD_DTL_AVALIABILITY"."RELEASE_ID" = "RELEASES"."ID"
) LEFT OUTER JOIN "IQMS"."EPLANT" "EPLANT"
  ON "V_ORD_DTL_AVALIABILITY"."EPLANT_ID" = "EPLANT"."ID"
) LEFT OUTER JOIN "IQMS"."ORD_DETAIL" "ORD_DETAIL"
  ON "V_ORD_DTL_AVALIABILITY"."ORD_DETAIL_ID" = "ORD_DETAIL"."ID"
) LEFT OUTER JOIN "IQMS"."CURRENCY" "CURRENCY"
  ON "ORDERS"."CURRENCY_ID" = "CURRENCY"."ID";
