-- Source: Crystal Report "Orders Percent Complete"
SELECT
  "ORDERS"."ORDERNO",
  "ORD_DETAIL"."ORD_DET_SEQNO",
  "ARCUSTO"."COMPANY",
  "ORD_DETAIL"."ARINVT_ID",
  "ARINVT"."ITEMNO",
  "ARINVT"."REV",
  "ARINVT"."DESCRIP",
  "ORD_DETAIL"."TOTAL_QTY_ORD",
  "ORD_DETAIL"."CUMM_SHIPPED",
  "RELEASES"."REQUEST_DATE",
  "RELEASES"."PROMISE_DATE",
  "RELEASES"."QUAN",
  "ORDERS"."EPLANT_ID",
  "EPLANT"."COMPANY",
  "ORD_DETAIL"."MISC_ITEMNO",
  "ORD_DETAIL"."MISC_ITEM"
FROM (((((
  "IQMS"."ORDERS" "ORDERS"
  LEFT OUTER JOIN "IQMS"."ORD_DETAIL" "ORD_DETAIL"
    ON "ORDERS"."ID" = "ORD_DETAIL"."ORDERS_ID"
) LEFT OUTER JOIN "IQMS"."ARCUSTO" "ARCUSTO"
  ON "ORDERS"."ARCUSTO_ID" = "ARCUSTO"."ID"
) LEFT OUTER JOIN "IQMS"."EPLANT" "EPLANT"
  ON "ORDERS"."EPLANT_ID" = "EPLANT"."ID"
) LEFT OUTER JOIN "IQMS"."RELEASES" "RELEASES"
  ON "ORD_DETAIL"."ID" = "RELEASES"."ORD_DETAIL_ID"
) LEFT OUTER JOIN "IQMS"."ARINVT" "ARINVT"
  ON "ORD_DETAIL"."ARINVT_ID" = "ARINVT"."ID"
ORDER BY
  "ORDERS"."ORDERNO",
  "ORD_DETAIL"."ORD_DET_SEQNO";
