-- Source: Work Order List Summary
SELECT
  "WORKORDER"."ID",
  "STANDARD"."MFGNO",
  "ARCUSTO"."COMPANY",
  "STANDARD"."CNTR_TYPE",
  "STANDARD"."SETUPHRS",
  "WORKORDER"."CYCLES_REQ",
  "WORKORDER"."PRODHRS",
  "WORKORDER"."BUCKET",
  "WORKORDER"."START_TIME",
  "WORKORDER"."END_TIME",
  "ARINVT"."DESCRIP",
  "WORKORDER"."EPLANT_ID",
  "STANDARD"."MFG_TYPE",
  "EPLANT"."COMPANY",
  "WORKORDER"."ORIGIN",
  "PTORDER_REL"."REL_DATE",
  "PTORDER_REL"."ORDERNO",
  "PTORDER_REL"."REL_QUAN",
  "ORDERS"."DATE_TAKEN"
FROM ((((((
  "IQMS"."WORKORDER" "WORKORDER"
  LEFT OUTER JOIN "IQMS"."STANDARD" "STANDARD"
    ON "WORKORDER"."STANDARD_ID" = "STANDARD"."ID"
) LEFT OUTER JOIN "IQMS"."ARCUSTO" "ARCUSTO"
  ON "WORKORDER"."ARCUSTO_ID" = "ARCUSTO"."ID"
) LEFT OUTER JOIN "IQMS"."EPLANT" "EPLANT"
  ON "WORKORDER"."EPLANT_ID" = "EPLANT"."ID"
) LEFT OUTER JOIN "IQMS"."PTORDER" "PTORDER"
  ON "WORKORDER"."ID" = "PTORDER"."WORKORDER_ID"
) LEFT OUTER JOIN "IQMS"."ARINVT" "ARINVT"
  ON "STANDARD"."ARINVT_ID_MAT" = "ARINVT"."ID"
) LEFT OUTER JOIN "IQMS"."PTORDER_REL" "PTORDER_REL"
  ON "PTORDER"."ID" = "PTORDER_REL"."PTORDER_ID"
) LEFT OUTER JOIN "IQMS"."ORDERS" "ORDERS"
  ON "PTORDER_REL"."ORDERNO" = "ORDERS"."ORDERNO"
ORDER BY
  "STANDARD"."MFG_TYPE",
  "WORKORDER"."ID",
  "PTORDER_REL"."ORDERNO",
  "PTORDER_REL"."REL_DATE";
