SELECT
  V_RT_PART_NUMBERS.EQNO AS work_center,
  V_RT_PART_NUMBERS.CNTR_DESC AS work_center_desc,
  V_RT_PART_NUMBERS.ITEMNO AS item_no,
  V_RT_PART_NUMBERS.DESCRIP AS description,
  V_RT_PART_NUMBERS.MFGNO AS mfg_no,
  V_RT_PART_NUMBERS.PARTSTOGO AS parts_to_go,
  V_RT_PART_NUMBERS.HOURS_LEFT AS hours_left,
  V_RT_PART_NUMBERS.STD_CYCLE AS std_cycle,
  V_RT_PART_NUMBERS.LAST_CYCLE AS last_cycle,
  V_RT_PART_NUMBERS.AVG_CYCLE AS avg_cycle,
  V_RT_PART_NUMBERS.ACTCAV AS act_cav,
  V_RT_PART_NUMBERS.STDCAV AS std_cav,
  V_RT_PART_NUMBERS.SHIFT_UP AS shift_up,
  V_RT_PART_NUMBERS.SHIFT_DWN AS shift_dwn,
  V_RT_PART_NUMBERS.DOWN_CODE AS down_code,
  V_RT_PART_NUMBERS.DOWN_DESCRIP AS down_descrip,
  V_RT_PART_NUMBERS.DWN_ST_TIME AS down_start_time,
  V_RT_PART_NUMBERS.WORKORDER_ID AS workorder_id,
  V_RT_PART_NUMBERS.CUSTNO AS cust_no,
  V_RT_PART_NUMBERS.PRIORITY_LEVEL AS priority_level,
  V_RT_PART_NUMBERS.HAS_QC_ISSUES AS has_qc_issues,
  V_RT_PART_NUMBERS.QC_ISSUE_COUNT AS qc_issue_count,
  V_RT_PART_NUMBERS.RUN_QTY AS run_qty,
  V_RT_PART_NUMBERS.OPDESC AS op_desc,
  V_RT_PART_NUMBERS.OPNO AS op_no,
  V_RT_PART_NUMBERS.START_TIME AS start_time
FROM IQMS.V_RT_PART_NUMBERS V_RT_PART_NUMBERS
WHERE V_RT_PART_NUMBERS.PK_HIDE IS NULL
  AND (V_RT_PART_NUMBERS.IS_VIRTUAL IS NULL OR V_RT_PART_NUMBERS.IS_VIRTUAL IN (' ', 'N'))
ORDER BY V_RT_PART_NUMBERS.EQNO
