SELECT
  PTORDER.WORKORDER_ID AS job_id,
  ARINVT.ITEMNO AS item_id,
  SUM(COALESCE(XCPT.QTY, 0)) AS required_qty,
  CAST(NULL AS NUMBER) AS issued_qty
FROM IQMS.XCPT_MAT_REQ XCPT
INNER JOIN IQMS.PTORDER PTORDER
  ON XCPT.COST_OBJECT_SOURCE = 'PTORDER'
  AND XCPT.COST_OBJECT_ID = PTORDER.ID
INNER JOIN IQMS.ARINVT ARINVT
  ON XCPT.ARINVT_ID = ARINVT.ID
WHERE PTORDER.WORKORDER_ID = :jobId
  AND COALESCE(XCPT.QTY, 0) > 0
GROUP BY
  PTORDER.WORKORDER_ID,
  ARINVT.ITEMNO
