SELECT
  V_SCHED_HRS_TO_GO.WORKORDER_ID AS job_id,
  COALESCE(PTALLOCATE.PROMISE_DATE, PTALLOCATE.MUST_SHIP_DATE) AS due_date,
  WORKORDER.STATUS AS status,
  V_SCHED_HRS_TO_GO.HOURS_TO_GO AS remaining_work,
  WORK_CENTER.EQNO AS resource_id,
  V_SCHED_HRS_TO_GO.CNTR_SEQ AS operation_seq,
  V_SCHED_HRS_TO_GO.ID AS operation_id,
  V_SCHED_HRS_TO_GO.PROD_START_TIME AS prod_start_time,
  V_SCHED_HRS_TO_GO.PROD_END_TIME AS prod_end_time,
  V_SCHED_PARTS_TO_GO.PARTS_TO_GO AS parts_to_go,
  ARINVT.ITEMNO AS part,
  ARINVT.DESCRIP AS description
FROM IQMS.V_SCHED_HRS_TO_GO V_SCHED_HRS_TO_GO
LEFT OUTER JOIN IQMS.WORK_CENTER WORK_CENTER
  ON V_SCHED_HRS_TO_GO.WORK_CENTER_ID = WORK_CENTER.ID
LEFT OUTER JOIN IQMS.PTORDER PTORDER
  ON V_SCHED_HRS_TO_GO.WORKORDER_ID = PTORDER.WORKORDER_ID
LEFT OUTER JOIN IQMS.WORKORDER WORKORDER
  ON V_SCHED_HRS_TO_GO.WORKORDER_ID = WORKORDER.ID
LEFT OUTER JOIN IQMS.V_SCHED_PARTS_TO_GO V_SCHED_PARTS_TO_GO
  ON V_SCHED_HRS_TO_GO.ID = V_SCHED_PARTS_TO_GO.CNTR_SCHED_ID
LEFT OUTER JOIN IQMS.PARTNO PARTNO
  ON PTORDER.PARTNO_ID = PARTNO.ID
LEFT OUTER JOIN IQMS.PTORDER_REL PTORDER_REL
  ON PTORDER.ID = PTORDER_REL.PTORDER_ID
LEFT OUTER JOIN IQMS.PTALLOCATE PTALLOCATE
  ON PTORDER_REL.PTALLOCATE_ID = PTALLOCATE.ID
LEFT OUTER JOIN IQMS.ARINVT ARINVT
  ON PARTNO.ARINVT_ID = ARINVT.ID
WHERE V_SCHED_HRS_TO_GO.WORKORDER_ID = :jobId
  AND (WORK_CENTER.IS_VIRTUAL IS NULL OR WORK_CENTER.IS_VIRTUAL IN (' ', 'N'))
