SELECT
  V_SCHED_HRS_TO_GO.ID AS operation_id,
  V_SCHED_HRS_TO_GO.WORKORDER_ID AS job_id,
  WORK_CENTER.EQNO AS resource_id,
  V_SCHED_HRS_TO_GO.CNTR_SEQ AS sequence,
  0 AS standard_rate,
  0 AS actual_rate,
  V_SCHED_HRS_TO_GO.HOURS_TO_GO AS remaining_time
FROM IQMS.V_SCHED_HRS_TO_GO V_SCHED_HRS_TO_GO
LEFT OUTER JOIN IQMS.WORK_CENTER WORK_CENTER
  ON V_SCHED_HRS_TO_GO.WORK_CENTER_ID = WORK_CENTER.ID
WHERE V_SCHED_HRS_TO_GO.WORKORDER_ID = :jobId
