SELECT
  WO_PART.WORKORDER_ID AS job_id,
  ARINVT.ITEMNO AS item_id,
  WO_PART.QTY AS required_qty,
  COALESCE(WO_PART.QTY_ISSUED, 0) AS issued_qty
FROM IQMS.WO_PART WO_PART
LEFT OUTER JOIN IQMS.PARTNO PARTNO
  ON WO_PART.PARTNO_ID = PARTNO.ID
LEFT OUTER JOIN IQMS.ARINVT ARINVT
  ON PARTNO.ARINVT_ID = ARINVT.ID
WHERE WO_PART.WORKORDER_ID = :jobId
  AND WO_PART.QTY > 0
