-- Get unit prices for jobs from ORD_DETAIL
-- Links PTORDER_REL -> ORDERS -> ORD_DETAIL to get unit price
SELECT 
  PTORDER_REL.PTORDER_ID,
  WORKORDER.ID AS WORKORDER_ID,
  ORD_DETAIL.UNIT_PRICE,
  WORKORDER.CYCLES_REQ AS QTY_ORDERED,
  (ORD_DETAIL.UNIT_PRICE * WORKORDER.CYCLES_REQ) AS TOTAL_ORDER_VALUE
FROM IQMS.PTORDER_REL
INNER JOIN IQMS.PTORDER ON PTORDER_REL.PTORDER_ID = PTORDER.ID
INNER JOIN IQMS.WORKORDER ON PTORDER.WORKORDER_ID = WORKORDER.ID
LEFT JOIN IQMS.ORDERS ON ORDERS.ORDERNO = PTORDER_REL.ORDERNO
LEFT JOIN IQMS.ORD_DETAIL ON ORD_DETAIL.ORDERS_ID = ORDERS.ID
WHERE PTORDER_REL.ORDERNO IS NOT NULL
  AND ORD_DETAIL.UNIT_PRICE IS NOT NULL
  AND ROWNUM <= 5000
