SELECT
  WORK_CENTER.EQNO AS resource_id,
  WORK_CENTER.MFG_TYPE AS resource_type,
  COALESCE(WORK_CENTER.DAILY_CAPACITY, 0) AS available_capacity,
  COALESCE(
    (SELECT SUM(V_SCHED_HRS_TO_GO.HOURS_TO_GO)
     FROM IQMS.V_SCHED_HRS_TO_GO V_SCHED_HRS_TO_GO
     WHERE V_SCHED_HRS_TO_GO.WORK_CENTER_ID = WORK_CENTER.ID),
    0
  ) AS scheduled_load
FROM IQMS.WORK_CENTER WORK_CENTER
WHERE (WORK_CENTER.IS_VIRTUAL IS NULL OR WORK_CENTER.IS_VIRTUAL IN (' ', 'N'))
